apiVersion: v2
description: A Helm chart for the Openstack Masakari Service
name: masakari
version: 0.1.0
appVersion: "bobcat"
dependencies:
  - name: mariadb
    repository: file://../../common/mariadb
    version: 0.12.1
  - name: rabbitmq
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.7.2
  - name: memcached
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.5.2
  - name: utils
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.16.1
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.0.0
  - name: linkerd-support
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.0.0
