nameOverride: ""
fullnameOverride: ""

securityContext:
  privileged: true
  runAsUser: 0

masakari_monitors:
  imagePullPolicy: Always

monitoring_agent:
  imagePullPolicy: Always
  log_level: TRACE
  config_path: /config.yaml

owner-info:
  support-group: compute-storage-api
  service: masakari
  maintainers:
  - Felix Goldmann
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/openstack/masakari-hypervisor-agents
