---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-{{.Values.name}}
  labels:
    {{- include "mariadb.labels" (list $ "noversion" "mariadb" "secret" "database") | indent 4 }}
type: Opaque
data:
  root-password: {{ include "mariadb.root_password" . | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-{{.Values.name}}-initdb-root
  labels:
    {{- include "mariadb.labels" (list $ "noversion" "mariadb" "secret" "database") | indent 4 }}
type: Opaque
data:
  init.sql: |
{{ include (print .Template.BasePath "/initdb/_init-root.sql.tpl") . | trim | b64enc | indent 4 }}
