apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-etc
  labels:
    system: openstack
    type: configuration
    component: {{ .Release.Name }}
data:
  masakarimonitors.conf: |
{{ include (print .Template.BasePath "/etc/_masakarimonitors.conf.tpl") . | b64enc | indent 4 }}
  agent-checks.conf: |
{{ include (print .Template.BasePath "/etc/_agent-checks.conf.tpl") . | b64enc | indent 4 }}
