kind: Service
apiVersion: v1

metadata:
  name: {{ .Release.Name }}-api
  labels:
    system: openstack
    type: api
    component: {{ .Chart.Name }}
  annotations:
    {{- include "utils.linkerd.pod_and_service_annotation" . | indent 4 }}
spec:
  selector:
    name: {{ .Release.Name }}-api
  ports:
    - name: masakari-api
      port: {{.Values.masakariApiPortInternal}}
