apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cleanupdb-script
  labels:
    system: openstack
    type: configuration
    component: {{ .Release.Name }}
data:
  cleanup.sh: |
    #!/bin/bash
    # This script cleans up old data from the Masakari database.

    # MariaDB command
    MARIADB_CMD="mariadb -h \"$MASAKARI_DB_HOST\" -u \"$MASAKARI_DB_USER\" --password=\"$MASAKARI_DB_PASSWORD\" --database=\"$MASAKARI_DB_NAME\" -e "

    # Function to delete rows
    # First input is the delete statement
    # Second input is the select statement
    delete_function() {
      if [ -n "$DAYS" ] && [ -n "$1" ] && [ -n "$2" ]; then
        echo "Number of days: $DAYS"
        echo "Delete statement: $1"
        echo "Select Statement: $2"

        # MariaDB command to fetch rows to be deleted
        $MARIADB_CMD "$2"
        if [ $? -ne 0 ]; then
          echo "Failed to fetch rows."
          exit 1
        fi

        # MariaDB command to delete rows
        $MARIADB_CMD "$1"
        if [ $? -ne 0 ]; then
          echo "Failed to delete rows."
          exit 1
        fi
      else 
        echo "Failed to delete rows. One or more variables are empty."
        exit 1
      fi
    }

    # Queries for notifications table and deletes rows older than $DAYS
    NOTIFICATION_SELECT_QUERY="SELECT * FROM notifications WHERE updated_at < NOW() - INTERVAL $DAYS DAY;"
    NOTIFICATION_DELETE_QUERY="DELETE FROM notifications WHERE updated_at < NOW() - INTERVAL $DAYS DAY;"
    delete_function "$NOTIFICATION_DELETE_QUERY" "$NOTIFICATION_SELECT_QUERY"
