# ConfigMap which handles upload to Swift Obeject storage
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-upload-script
  labels:
    system: openstack
    type: configuration
    component: {{ .Release.Name }}
data:
  upload.sh: |
    #!/bin/bash
    # Define BackupPath
    BACKUP_PATH="${BACKUP_PATH:-/backup}"
    OBJECT_NAME="${OBJECT_NAME:-masakari}"
    EXPIRATION_TIME="${EXPIRATION_TIME:-5260032}"
    echo "List Expiration Time: $EXPIRATION_TIME"
    MASAKARI_ENGINE_VERSION=$(cat "$BACKUP_PATH/$(date +"%Y%m%d")/masakari-engine-version.txt")
    echo "Masakari-Engine-Version: $MASAKARI_ENGINE_VERSION"
    # Upload the backup to Swift if path is not empty
    if [ -n "$(ls -A "$BACKUP_PATH")" ]; then
      swift upload --object-name "$OBJECT_NAME" db_backup "$BACKUP_PATH" \
      -m "Masakari-Engine-Version:$MASAKARI_ENGINE_VERSION" \
      -H "X-Delete-After":$EXPIRATION_TIME
    else
      echo "No files to upload in $BACKUP_PATH"
      exit 1
    fi
