apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backup-script
  labels:
    system: openstack
    type: configuration
    component: {{ .Release.Name }}
data:
  backup.sh: |
    #!/bin/bash
    set -e

    # Define variables
    DB_PATH="${DB_PATH:-/database/masakari.sqlite}"
    BACKUP_ROOT_PATH="${BACKUP_PATH:-/backup}"
    BACKUP_PATH="$BACKUP_ROOT_PATH/$(date +"%Y%m%d")"
    TIMESTAMP=$(date +"%Y%m%d%H%M%S")
    BACKUP_FILE="$BACKUP_PATH/database_backup_$TIMESTAMP.db"
    COMPRESSED_BACKUP_FILE="$BACKUP_FILE.gz"

    # Function to handle errors
    error_exit() {
      echo "$1" 1>&2
      exit 1
      }

    echo "Clear the backup directory"
    rm -rf "$BACKUP_ROOT_PATH"/* || error_exit "Failed to clear backup directory: $BACKUP_ROOT_PATH"

    echo "Create a backup"
    mkdir -p "$BACKUP_PATH" || error_exit "Failed to create backup directory: $BACKUP_PATH"
    sqlite3 "$DB_PATH" ".backup '$BACKUP_FILE'" || error_exit "Failed to create database backup: $BACKUP_FILE"
    masakari-engine --version > "$BACKUP_PATH/masakari-engine-version.txt" || error_exit "Failed to get masakari-engine version"

    echo "Compress the backup"
    gzip "$BACKUP_FILE" || error_exit "Failed to compress backup file: $BACKUP_FILE"

    echo "Verify if backup exists and is not empty"
    if [ -s "$COMPRESSED_BACKUP_FILE" ]; then
      echo "Backup successful: $COMPRESSED_BACKUP_FILE"
    else
      error_exit "Backup failed: Compressed backup file not created or is empty."
    fi
