# ConfigMap which handles upload to Swift Obeject storage
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-upload-script
  labels:
    system: openstack
    type: configuration
    component: {{ .Release.Name }}
data:
  upload.sh: |
    #!/bin/bash
    # Define BackupPath
    BACKUP_PATH="${BACKUP_PATH:-/backup}"
    OBJECT_NAME="${OBJECT_NAME:-masakari}"
    # Upload the backup to Swift if path is not empty
    if [ -n "$(ls -A "$BACKUP_PATH")" ]; then
      swift upload --object-name "$OBJECT_NAME" db_backup "$BACKUP_PATH/*"
    else
      echo "No files to upload in $BACKUP_PATH"
    fi
