apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: masakari-database
spec:
  storageClassName:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
