apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-etc
  labels:
    system: openstack
    type: configuration
    component: {{ .Release.Name }}
data:
  masakari.conf: |
{{ include (print .Template.BasePath "/etc/_masakari.conf.tpl") . | indent 4 }}
  logging.ini: |
{{ include "loggerIni" .Values.logging | indent 4 }}
  statsd-exporter.yaml: |
    defaults:
      timer_type: histogram
      buckets: [.025, .1, .25, 1, 2.5]
      match_type: glob
      glob_disable_ordering: false
      ttl: 0 # metrics do not expire
  uwsgi.ini: |
{{ include (print .Template.BasePath "/etc/_uwsgi.ini.tpl") . | indent 4 }}
  policy.yaml: |
{{ include (print .Template.BasePath "/etc/_policy.yaml.tpl") . | indent 4 }}
