apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: masakari-backup
spec:
  storageClassName:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.sqlite.pvc_size }}
