apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: masakari-slack
spec:
  storageClassName:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
