apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-etc
  labels:
    system: openstack
    type: configuration
    component: {{ .Chart.Name }}
type: Opaque
data:
  secrets.conf: |
    {{ include (print .Template.BasePath "/etc/_secrets.conf.tpl") . | b64enc | indent 4 }}
  config.yaml: |
    {{ include (print .Template.BasePath "/etc/_monitoring.yaml.tpl") . | b64enc | indent 4 }}
stringData:
  slack_token: vault+kvv2:///secrets/global/masakari/slack/token
  host_down_username: hwconsole
  host_down_password: vault+kvv2:///secrets/shared/ironic/remoteboard-user/hwconsole/password
  db_password: vault+kvv2:///secrets/{{ .Values.global.region }}/shared/keystone-user/db-backup/password
