apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: masakari-seed
spec:
  requires:
  - monsoon3/domain-default-seed

  roles:
  - name: compute_admin
  - name: compute_viewer
  - name: cloud_compute_admin

  services:
  - name: masakari
    type: instance-ha
    description: Openstack Instances High Availability Service API
    endpoints:
    - interface: admin
      region: '{{ .Values.global.region }}'
      url: 'http://masakari-api.{{.Release.Namespace}}.svc.kubernetes.{{.Values.global.region}}.{{.Values.global.tld}}:{{.Values.masakariApiPortAdmin}}'
    - interface: internal
      region: '{{ .Values.global.region }}'
      url: 'http://masakari-api.{{.Release.Namespace}}.svc.kubernetes.{{.Values.global.region}}.{{.Values.global.tld}}:{{.Values.masakariApiPortInternal}}'
    - interface: public
      region: '{{ .Values.global.region }}'
      url: 'https://{{ include "masakari_api_endpoint_host_public" . }}:{{.Values.masakariApiPortPublic}}'

  domains:
  - name: Default
    users:
    - name: masakari
      description: Masakari API Service User
      password: {{ required ".Values.global.masakari_service_password is missing" .Values.global.masakari_service_password }}
      role_assignments:
      - project: service
        role: service
      - project: service
        role: cloud_compute_admin
