{{- if .Values.nanny.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: nova-nanny-secret
data:
  nanny_os_password: {{ required ".Values.nanny.keystone_password is missing" .Values.nanny.keystone_password | include "resolve_secret" | b64enc }}
{{- end }}
