{{- if and $.Values.pxcdb.enabled (not $.Values.pxcoperator.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ include "pxc-database.fullname" . }}
spec:
  backoffLimit: {{ $.Values.database.job.config.backoffLimit | default 6 | int }}
  activeDeadlineSeconds: {{ $.Values.database.job.config.activeDeadlineSeconds | default 300 | int }}
  ttlSecondsAfterFinished: {{ $.Values.database.job.config.ttlSecondsAfterFinished | default 120 | int }}
  template:
    metadata:
      labels:
        {{- include "percona-operator.labels" (list $ "version" "database" "job" "config") | indent 8 }}
      annotations:
        {{- if or (and (hasKey $.Values "global") (and (hasKey $.Values.global "linkerd_enabled") $.Values.global.linkerd_enabled) (and (hasKey $.Values.global "linkerd_requested") $.Values.global.linkerd_requested)) $.Values.database.job.linkerd.enabled }}
        linkerd.io/inject: enabled
        {{- end }}
        checksum/configmap: {{ include (print $.Template.BasePath "/pxcdb-configmap-db-job.yaml") $ | sha256sum }}
    spec:
      restartPolicy: {{ $.Values.mariadb.job.config.jobRestartPolicy | default "OnFailure" | quote }}
      serviceAccount: {{ include "pxc-database.fullname" . }}-pxcdb-job-db-config
      securityContext:
        fsGroup:  {{ $.Values.groupId.database | default 1001 | int }}
        supplementalGroups:
        - 1001
      {{- if and (hasKey $.Values.image.database "pullSecret") $.Values.image.database.pullSecret }}
      imagePullSecrets:
      - name: {{ include "commonPrefix" $ }}-{{$.Values.image.database.pullSecret}}
      {{- end }}
      containers:
      - name: cfg
        image: "{{ $.Values.image.database.registry }}/{{ $.Values.image.database.project }}/{{ $.Values.image.database.softwarename }}:{{ $.Values.image.database.softwareversion }}-{{ $.Values.image.database.imageversion | int }}"
        imagePullPolicy: {{ $.Values.image.database.pullPolicy | default "IfNotPresent" | quote }}
        securityContext:
          runAsUser:  {{ $.Values.userId.database | default 101 | int }}
          runAsGroup: {{ $.Values.groupId.database | default 101 | int }}
        {{- if and ($.Values.command) (hasKey $.Values.command "databasecfgjob") }}
        command:
{{ $.Values.command.databasecfgjob | toYaml | indent 8 }}
        {{- else }}
        command:
          - "sh"
          - "-c"
          - "/opt/mariadb/bin/entrypoint-job-config.sh"
        {{- end }}
        env:
        - name: MYSQL_PORT
          value: {{ (required ".services.database.frontend.ports.mysql.targetPort missing" $.Values.services.database.frontend.ports.mysql.targetPort) | quote }}
        {{- if not (hasKey $.Values.env "MARIADB_MONITORING_CONNECTION_LIMIT") }}
        - name: MARIADB_MONITORING_CONNECTION_LIMIT
          value: 3
        {{- end }}
        {{- range $envKey, $envValue := $.Values.env }}
          {{- if (has "databasecfgjob" $envValue.containerType) }}
            {{- if $envValue.value }}
        - name: {{ $envKey }}
          value: {{ $envValue.value | quote }}
            {{- end }}
            {{- if $envValue.secretName }}
              {{- range $userKey, $userValue := $.Values.mariadb.users }}
                {{- $requiredUsers := list "root" }}
                {{- if or ($.Values.monitoring.mysqld_exporter.enabled) (and ($.Values.proxy.enabled) (eq $.Values.proxy.type "proxysql")) }}
                  {{- $requiredUsers = append $requiredUsers "monitor" }}
                  {{- $requiredUsers = $requiredUsers | uniq | compact }}
                {{- end}}
                {{- if or (has $userKey $requiredUsers) $userValue.enabled }}
                  {{- if eq $userValue.secretName $envValue.secretName }}
        - name: {{ $envKey }}
          valueFrom:
            secretKeyRef:
              name: {{ include "commonPrefix" $ }}-{{ $envValue.secretName }}
              key: {{ $envValue.secretKey }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: {{ $.Values.resourceLimits.cpu.databasecfgjob | default 0.25 }}
          limits:
            memory: {{ $.Values.resourceLimits.memory.databasecfgjob | default "32Mi" | quote }}
        volumeMounts:
        - name: {{ include "commonPrefix" $ }}-mariadb-config-job-entrypoint-sh
          mountPath: /opt/mariadb/bin/entrypoint-job-config.sh
          subPath: entrypoint-job-config.sh
          readOnly: true
        - name: {{ include "commonPrefix" $ }}-mariadb-common-functions-extended-sh
          mountPath: /opt/mariadb/bin/common-functions-extended.sh
          subPath: common-functions-extended.sh
          readOnly: true
      volumes:
      {{- range $volumeMountsKey, $volumeMountsValue := $.Values.volumeMounts.database }}
        {{- if $volumeMountsValue.enabled }}
          {{- if $volumeMountsValue.type }}
            {{- if ne $volumeMountsValue.type "persistentVolume" }}
      - name: {{ include "commonPrefix" $ }}-{{ $volumeMountsKey }}
              {{- if eq $volumeMountsValue.type "secret"}}
        {{ $volumeMountsValue.type }}:
          secretName: {{ include "commonPrefix" $ }}-{{ $volumeMountsKey }}
              {{- else if eq $volumeMountsValue.type "hostPath" }}
        {{ $volumeMountsValue.type }}:
          path: {{ $volumeMountsValue.hostPath }}
              {{- else }}
          name: {{ include "commonPrefix" $ }}-{{ $volumeMountsKey }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      - name: {{ include "commonPrefix" $ }}-mariadb-config-job-entrypoint-sh
        configMap:
          name: {{ include "commonPrefix" $ }}-mariadb-config-job-entrypoint-sh
          defaultMode: 0750
      - name: {{ include "commonPrefix" $ }}-mariadb-common-functions-extended-sh
        configMap:
          name: {{ include "commonPrefix" $ }}-mariadb-common-functions-extended-sh
          defaultMode: 0755
{{- end }}