owner-info:
  service: otel
  support-group: observability
  maintainers:
  - name: timojohlo
  - name: kuckkuck
  - name: viennaa
  helm-chart-url: https://github.com/sapcc/helm-charts/system/opentelemetry


opentelemetry-operator:
  openTelemetry:
    prometheus:
      rules:
        create: false
        labels: {}
