owner-info:
  service: otel
  support-group: observability
  maintainers:
  - name: timojohlo
  - name: kuckkuck
  - name: viennaa
  helm-chart-url: https://github.com/sapcc/helm-charts/system/opentelemetry

opentelemetry-operator:
  nameOverride: "operator"

  # The required CRDs used by this dependency are version-controlled in this repository under ./crds.
  # This is required because there is no other Plugin that would install them, and because automatic CRD installs are not supported due to a limitation with helm, see [HIP0011](https://github.com/helm/community/blob/main/hips/hip-0011.md).
  crds:
    create: false
  admissionWebhooks:
    failurePolicy: 'Ignore'

    # If cert-manager should be used, the CRDs for cert-manager needs to exists before otel installs cert-manager.
    certManager:
      enabled: false
    autoGenerateCert:
      recreate: false
  manager:
    collectorImage:
      repository: DEFINED-IN-SECRETS
      tag: DEFINED-IN-SECRETS
    image:
      repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
      tag: v0.114.1
    deploymentAnnotations:
      vpa-butler.cloud.sap/update-mode: Auto
    serviceMonitor:
      enabled: true
  kubeRBACProxy:
    enabled: false

openTelemetry:
  customLabels: {}

  openSearchLogs:
    endpoint: DEFINED-IN-SECRETS
    username: DEFINED-IN-SECRETS
    password: DEFINED-IN-SECRETS
  cluster: DEFINED-IN-SECRETS
  region: DEFINED-IN-SECRETS
  logsCollector:
    enabled: false
  metricsCollector:
    enabled: false

  prometheus:
    serviceMonitor:
      enabled: false
    podMonitor:
      enabled: false
    additionalLabels: {}

testFramework:
  enabled: false
  image:
    registry: ghcr.io
    repository: cloudoperators/greenhouse-extensions-integration-test
    tag: main
  imagePullPolicy: IfNotPresent
