owner-info:
  service: otel
  support-group: observability
  maintainers:
  - name: timojohlo
  - name: kuckkuck
  - name: viennaa
  helm-chart-url: https://github.com/sapcc/helm-charts/system/opentelemetry

opentelemetry-operator:
  opentelemetry-operator:
    crds:
      create: false
    admissionWebhooks:
      failurePolicy: 'Ignore'
      create: true
      certManager:
        enabled: false
      autoGenerateCert:
        enabled: false
        recreate: false
    manager:
      collectorImage:
        repository: DEFINED-IN-SECRETS
        tag: DEFINED-IN-SECRETS
      deploymentAnnotations:
        vpa-butler.cloud.sap/update-mode: Auto
      prometheusRule:
        enabled: false
        defaultRules:
          enabled: false
    kubeRBACProxy:
      enabled: false
# Empty variables will fail during rollout
  openTelemetry:
    logsCollector:
      enabled: true
    metricsCollector:
      enabled: true
    openSearchLogs:
      endpoint: DEFINED-IN-SECRETS
      username: DEFINED-IN-SECRETS
      password: DEFINED-IN-SECRETS
    cluster: DEFINED-IN-SECRETS
    region: DEFINED-IN-SECRETS
    prometheus:
      additionalLabels: {}
      serviceMonitor:
        enabled: true
      podMonitor:
        enabled: true

  testFramework:
    enabled: false
    image:
      registry: ghcr.io
      repository: cloudoperators/greenhouse-extensions-integration-test
      tag: main
    imagePullPolicy: IfNotPresent
