{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  name: opentelemetry-collector-metrics
  labels:
    {{- include "plugin.labels" . | nindent 4 }}
    {{- include "plugin.prometheusLabels" . | nindent 4 }}
spec:
  endpoints:
  - port: prometheus
    relabelings:
      - regex: pod
        action: labeldrop
  - port: monitoring
    relabelings:
      - regex: pod
        action: labeldrop
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: {{ .Release.Namespace }}.opentelemetry.metrics
      app.kubernetes.io/managed-by: opentelemetry-operator
      app.kubernetes.io/part-of: opentelemetry
{{- end }}
