kind: Secret
apiVersion: v1

metadata:
  name: elektra
data:
  monsoon.dashboard.mail.user: {{ .Values.monsoon_dashboard_mail_user | b64enc }}
  monsoon.dashboard.mail.password: {{ .Values.monsoon_dashboard_mail_password | b64enc }}
  monsoon.openstack.auth.api.password: {{ .Values.monsoon_openstack_auth_api_password | b64enc}}
{{- if .Values.sentryDSN }}
{{- if .Values.sentryDSN }}{{ if ne .Values.sentryDSN "auto" }}
  sentryDSN: {{ .Values.sentryDSN | b64enc }}
{{- end }}
{{- end }}{{ end }}
{{- if and .Values.ingress.enabled .Values.ingress.tls_crt }}
  tls.crt: {{ .Values.ingress.tls_crt | b64enc }}
  tls.key: {{ .Values.ingress.tls_key | b64enc }}
{{- end }}
