apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "provider-khalkeon.fullname" . }}-ignitionv3-viewer-role
  labels:
  {{- include "provider-khalkeon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - metal.cobaltcore.dev
  resources:
  - ignitionv3s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal.cobaltcore.dev
  resources:
  - ignitionv3s/status
  verbs:
  - get