apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "provider-khalkeon.fullname" . }}-manager-role
  labels:
  {{- include "provider-khalkeon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - patch
  - watch
- apiGroups:
  - metal.cobaltcore.dev
  resources:
  - ignitionv3s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.cobaltcore.dev
  resources:
  - ignitionv3s/finalizers
  verbs:
  - update
- apiGroups:
  - metal.cobaltcore.dev
  resources:
  - ignitionv3s/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "provider-khalkeon.fullname" . }}-manager-rolebinding
  labels:
  {{- include "provider-khalkeon.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "provider-khalkeon.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "provider-khalkeon.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'